version: "3"


services:
  php:
    container_name: my_project_php
    build:
      context: .
      dockerfile: deploy/php-fpm/Dockerfile
    volumes:
      - ./my_project:/data/my_project
  nginx:
    container_name: my_project
    build:
      context: .
      dockerfile: deploy/nginx/Dockerfile
    volumes:
      - ./deploy/nginx/templates:/etc/nginx/templates
      - ./my_project:/data/my_project
    ports:
      - "8081:80"
    environment:
      - NGINX_CUSTOM_SERVER_NAME=project-2021.local
      - NGINX_SYMFONY_SERVER_NAME=project-symfony.local